require 'rubygems'
require 'active_support'
require 'active_support/test_case'
require 'test/unit'
require 'json'
require 'net/http'
require 'uri'
require 'yaml'
require 'mocha'
require File.dirname(__FILE__) + '/../lib/mq_proxy'